### ISSUE TITLE
Feature request: Make it work with defaultProps as well

### ISSUE THREAD

**Issue by aversini** [siddharthkp/react-docgen-external-proptypes-handler#4]
This library works very well for `propTypes` definitions, however it is not resolving for `defaultProps`.
Consider the example below (it's the same as in your README file), with the addition of a default value:

```jsx
import React from 'react'
import PropTypes from 'prop-types'

/* importing variable iconNames from .js file (js, jsx are supported, json is not) */
import iconNames from './icon-names.js'

const Icon = props => {
  /*implementation logic*/
}

Icon.propTypes = {
  /** Icon name */
  name: PropTypes.oneOf(iconNames).isRequired
}

Icon.defaultProps = {
  /** default Icon name */
  name: iconNames[0]
}

export default Icon
```

While using your library in react-styleguidist, it doesn't resolve the default value and simply show `iconNames[0]` instead of `"copy"`. It would be great to add support for `defaultProps` as well. 
Thanks @siddharthkp and @pasupuletics 👍

**Comment by pasupuletics** [comment]
@aversini , Raised an [PR](https://github.com/siddharthkp/react-docgen-external-proptypes-handler/pull/9) to support defaultProps.

**Comment by petermooibroek** [comment]
defaultProps support would be cool!
