### ISSUE TITLE
Question: How to integrate with @storybook/addon-info?

### ISSUE THREAD

**Issue by Bobgy** [siddharthkp/react-docgen-external-proptypes-handler#6]
I've been affected by this issue when using @storybook/addon-info which uses react-docgen to generate documentation. It's not very obvious how I could integrate this handler. May I get some help on this?

**Comment by siddharthkp** [comment]
Hi

I'm not sure if `@storybook/addon-info` allows adding custom handlers to react-docgen. You might want to raise an issue on that repo instead

**Comment by Bobgy** [comment]
got it, thank you for the reply @siddharthkp

**Comment by siddharthkp** [comment]
Went down the rabbit hole, seems like the way to get react-docgen info in storybook is to use [storybooks/babel-plugin-react-docgen](https://github.com/storybooks/babel-plugin-react-docgen). It doesn't support custom handlers yet, but there was an issue you might want to comment on: https://github.com/storybooks/babel-plugin-react-docgen/issues/22

**Comment by Bobgy** [comment]
@siddharthkp awesome! thank you so much!
